---
id: swamp_fortress_level_2
name: Swamp Fortress Level 2
width: 30
height: 64
visibility_tile: gui/area_invis
explored_tile: gui/area_unexplored
max_vis_distance: 20
max_vis_up_one_distance: 6
world_map_location: serpents_mire
on_rest:
  Disabled:
    message: There are too many enemies about.  You may not rest here.
location_kind: Underground
generate: false
layers:
  - terrain_base
  - terrain_border
  - walls
  - walls_top
  - prop
  - object
  - object_interior
  - decoration
  - walls_aerial
  - aerial
  - aerial_prop
entity_layer: 7
actors: []
props:
  - id: door_single_02
    location:
      x: 8
      y: 41
    enabled: true
  - id: chest_xl_level5_armor
    location:
      x: 6
      y: 53
    enabled: true
  - id: chest_small
    location:
      x: 21
      y: 50
    items:
      - quantity: 1
        item:
          id: note_to_irhan
          adjectives: []
      - quantity: 500
        item:
          id: coin
          adjectives: []
    enabled: true
  - id: door_single_04
    location:
      x: 20
      y: 57
    enabled: true
  - id: transition_hint
    location:
      x: 20
      y: 61
    enabled: true
encounters:
  - id: irhan
    location:
      x: 10
      y: 30
    size:
      width: 12
      height: 10
transitions:
  - from:
      x: 7
      y: 3
    size: 2by3
    to:
      Area:
        id: swamp_fortress_level_1
        x: 106
        y: 48
    hover_text: To Level 1
    image_display: empty
  - from:
      x: 20
      y: 61
    size: 2by3
    to: WorldMap
    hover_text: To World Map
    image_display: empty
triggers:
  - kind:
      OnPlayerEnter:
        location:
          x: 17
          y: 24
        size:
          width: 10
          height: 10
    on_activate:
      - fire_script:
          id: swamp_fortress
          func: on_activate_irhan
    initially_enabled: true
terrain:
  kinds:
    - interior_dirt
    - interior_tile
    - fancy_carpet
    - interior_wood01
    - interior_wood02
  entries: ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP//////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP//////////////////////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP//////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP//////////////////////////////////////////////AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP///////////////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/////////////////////////////////////////////////////////wD/AP8A/wD/AP8A/wD/AP8A/////////////////////////////////////////////////////////////////wD/AP8A/wD/AP8A/////////////////////////////////////////////////////////////////wD/AP8A/wD/AP8A/////////////////////////////////////////////////////////////////wD/AP8A/wD/AP8A/////////////////////////////////////////////////////////////////wD/AP8A/wD/AP////////////////////////////////////////////////8B/wH/Af8B/wH/Af8B/wD/AP8A/wD/AP8B//////////////////////////////////////////////8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B//////////////////////////////////////////////8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B//////////////////////////////////////////////8B/wH/Af8C/wL/Av8C/wH/Af8B/wH/Af8B//////////////////////////////////////////////8B/wH/Af8C/wL/Av8C/wH/Af8B/wH/Af8B//////////////////////////////////////////////8B/wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/////////////////////////////////////////////////wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B/////////////////////////////////////////////////wH/Af8B/wH/Af8B/wH/Af8B/wH/Af8B//////////////////////////////////////////////////////8D/wH/Af8B/wH///////////////////////////////////////////////////////////////////8D//////////////////////////////////////////////////////////////////////////////8D/////////////////////////////////////////////////////////////////////////wP/A/8D/wP/A///////BP8E/wT/BP///////////////////////////////////////////////////wP/A/8D/wP/A/8D/wP/BP8E/wT/BP///////////////////////////////////////////////////wP/A/8D/wP/A/8D/wP/BP8E/wT/BP///////////////////////////////////////////////////wP/A/8D/wP/A/8D/wP/BP8E/wT/BP////////////////////////////////////////////////////////////////////////8E//////////////////////////////////////////////////////////////////////////////8A//////////////////////////////////////////////////////////////////////////////8A//////////////////////////////////////////////////////////////////////////////8A////////////////////////////////////////////////////
walls:
  kinds:
    - interior_brick
  entries: AAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wD/AP8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AP8A/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AAAB/wAAAf8AAAH/AP8A/wAAAf8AAAH/AAAB/wAAAf8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A
layer_set:
  tileset/fancy_carpet_outer_edge_se: ABAAJA==
  tileset/bucket_full: ABgAHA==
  tileset/interior_brick_inner_edge_sw: AA4AKgAOAAAAGgAqABgABAAQAD4AGgAS
  tileset/cabinet_top_04: ABgALg==
  tileset/interior_brick_inner_edge_ne: AAAADAACACgAAgA4
  tileset/wall_interior_brick_outer_edge_se: AAYALAAQABgAEgAU
  tileset/book02: AA0AGw==
  tileset/fancy_carpet_outer_edge_sw: AAYAJA==
  tileset/bar_horiz_w: AA4AGw==
  tileset/fancy_carpet_outer_edge_n: AA4AHgAIAB4ACgAeAAwAHg==
  tileset/wall_interior_brick_outer_edge_sw: AAoALAAOAAYAGAAU
  tileset/fancy_carpet_base: AAgAIAAIACIACgAiAAwAIgAOACIADgAgAAwAIAAKACA=
  table_large01: ABYAJA==
  tileset/fancy_carpet_outer_edge_ne: ABAAHg==
  tileset/cabinet_med03: AAQAIg==
  tileset/interior_brick_inner_edge_se: AAAAAAACABYAEAAqAAIAKgAYAD4AEAAS
  tileset/wall_interior_brick_outer_edge_s: AAAAAgACAAIABAACAAYAAgAIAAIACgACAA4ALAAQACwAEgAsAAIALAAEACwADAAsAAIAGAAEABgABgAYAAgAGAAKABgADAACAA4AAgAQAAYAEgAGABQABgAUACwAFgAGABgABgAWACwAGAAsABoALAAQABQADAAYAA4AGAAaABQ=
  tileset/cabinet_bot_02: ABIAMA==
  tileset/interior_wood02_base: ABQAMAAWADAAGAAwABIAMgAUADIAFgAyABgAMgASADQAFgA0ABgANAASADYAFAA2ABYANgAYADYAFAA0ABIAMAAUADg=
  tileset/papers02: ABYAJA==
  tileset/interior_brick_outer_edge_s: AAIAAAAEAAAABgAAAAgAAAAKAAAAEgAqABQAKgAEACoADAAqAAQAFgAGABYACAAWAAoAFgAMAAAAEAAEABIABAAUAAQAFgAqABgAKgAWAAQAAAA+AAIAPgAEAD4ABgA+AAgAPgAKAD4ADAA+AA4APgAaAD4AHAA+AAwAFgAOABY=
  tileset/cabinet_top_02: ABIALg==
  tileset/interior_brick_outer_edge_e: AAAAAgAAAAQAAAAGAAAACAAAAAoAAgAYAAIAGgACABwAAgAeAAIAIAACADIAAgAwABAALAAQAC4AAgAiAAIAJAACACYAAgAsAAIALgACADQAAgA2ABIAOgASADwAEgA+ABwACAAcAAoAHAAMABwAHgAcACAAHAAcABwABgAQABQAEgAOABwADgASABAAHAAQABwAEgAcABQAHAAWABwAGAAcABo=
  tileset/fancy_carpet_outer_edge_s: AAgAJAAKACQADAAkAA4AJA==
  tileset/castle01_doorway: AAcAAg==
  tileset/bottles03: AAcAGw==
  tileset/interior_tile_base: AAQAJgAEACgABgAoAAIAJAAEACQABgAkAAYAJgAIACQACAAmAAgAKAAKACgADAAoAA4AKAAKACoADAAqAA4AKgAQACoACgAkAAwAJAAOACQACgAmAAwAJgAOACYAEgAkABAAJgASACYAEAAoABIAKAAUACQAFgAkABgAJAAUACYAFgAmABgAJgAaACYAFAAoABYAKAAYACgAGgAoABoAGgAYABwAGgAcABgAHgAaAB4AGAAgABoAIAAYACIAGgAiABAAHAASABwAFAAcABYAHAAQAB4AEgAeABQAHgAWAB4AEAAgABIAIAAUACAAFgAgABAAIgASACIAFgAiAAwAGgAOABoADAAcAA4AHAAMAB4ADgAeAAIAGgAEABoABgAaAAgAGgAKABoAAgAcAAQAHAAGABwACAAcAAoAHAACAB4ABAAeAAgAHgAKAB4AAgAgAAQAIAACACIABAAiAAYAIgAQACQAFAAiAAYAIAAGAB4=
  tileset/interior_tile_base_variant1: ABoAJA==
  bed_small01: ABUALw==
  tileset/interior_dirt_base: ABAAEgAQABQAEAAWABAAGAASABgAFAAYABYAGAAYABgAEAAaABIAGgAUABoAFgAaABgAGgAaAA4AGgAQABIAEgAUABIAFgASABgAEgAaABIAEgAUABQAFAAWABQAGAAUABoAFAASABYAFAAWABYAFgAYABYAGgAWABQACAAWAAgAGAAIABQACgAWAAoAGAAKABQADAAWAAwAGAAMABQADgAWAA4AGAAOABQAEAAWABAAGAAQAA4ACAAQAAgAEgAIAA4ACgAQAAoAEgAKAA4ADAAQAAwAEgAMAAoADgAMAA4ADgAOABAADgASAA4ACgAQAAwAEAAOABAAEAAQABIAEAAKAAQADAAEAAoABgAMAAYACgAIAAwACAAKAAoADAAKAAoADAAMAAwAAAAEAAIABAAEAAQABgAEAAgABAAAAAYAAgAGAAQABgAGAAYACAAGAAAACAACAAgABAAIAAYACAAIAAgAAAAKAAIACgAEAAoABgAKAAgACgAAAAwAAgAMAAQADAAGAAwACAAMABQAOgAUADwAFAA+
  tileset/fancy_carpet_outer_edge_w: AAYAIAAGACI=
  tileset/shield01: ABEAGQ==
  tileset/interior_wood01_base: AAQAMAAEADIABAA0AAQANgAGADAACAAwAAoAMAAMADAABgAyAAYANAAGADYACAAyAAoAMgAIADQACgA0AAgANgAKADYADAAyAA4AMgAQADIADAA0AA4ANAAQADQADAA2AA4ANgAQADYACAAsAAgALgAIACo=
  tileset/bar_horiz_c: AAYAGwAIABsACgAbAAwAGw==
  tileset/wine_bottle02: ABgANQ==
  tileset/fancy_carpet_outer_edge_e: ABAAIAAQACI=
  tileset/bar_horiz_e: AAQAGw==
  tileset/interior_brick_inner_edge_nw: ABoAKAAaADg=
  tileset/cabinet_bot_01: ABgAMA==
  tileset/table01: ABgANgAEADY=
  tileset/interior_brick_outer_edge_n: AAIADAAEAAwABgAMAAgADAAKAAwADAAMAA4ADAAQAAwADgAoABAAKAASACgAFAAoAAQAKAAMACgAFgAoABgAKAAEADgABgA4AAgAOAAKADgADAA4AA4AOAAQADgAGAA4
  tileset/chair07: AAUAMg==
  tileset/fancy_carpet_outer_edge_nw: AAYAHg==
  tileset/bucket_empty: AAIACg==
  tileset/interior_brick_outer_edge_se: ABAAMAAGACoAEAAWABIAEg==
  tileset/interior_brick_outer_edge_ne: ABIADAAGACgAEgA4
  tileset/cabinet_wide04: AAQALg==
  tileset/swords01: AAsAAw==
  tileset/ropes01: AA8AMw==
  tileset/swords02: AAYAGQ==
  tileset/bottles01: AAQAGw==
  tileset/interior_brick_outer_edge_sw: AA4AMAAKACoADgAEABgAEg==
  tileset/wine_bottle01: AAQANQ==
  tileset/rug_small01: ABUAMw==
  tileset/papers: ABcAJQ==
  tileset/interior_brick_outer_edge_nw: AAoAKAAWADg=
  tileset/cabinet_wide01: AAIAAw==
  tileset/interior_brick_base: AAAADgAAABAAAgAOAAQADgAGAA4AAgAQAAgADgAKAA4AAAASAAIAEgAAABQAAgAUAAAAFgAAABgAAAAaAAAAHAAAAB4AAAAgAAAAMAAAADIAAAAiAAAAJAAAACYAAAAoAAAAKgAAACwAAAAuAAQAEAAGABAACAAQAAoAEAAEABIABgASAAgAEgAKABIABAAUAAYAFAAIABQACgAUABAAAAASAAAAFAAAABAAAgASAAIAFAACAAAANAAcACQAHAAmABwAKAAcACoAHAAiABwAHgAcACAAGgAMABwADAAaAAoAHAAKABYAAAAYAAAAGgAAABwAAAAWAAIAGAACABoAAgAcAAIAGgAEABwABAAaAAYAHAAGABoACAAcAAgAHAAsABwALgAcADAAHAAyABwANAAAADYAAAA4AAAAOgAAADwAAgA6AAQAOgACADwABAA8AAYAOgAIADoACgA6AAwAOgAOADoAEAA6AAYAPAAIADwACgA8AAwAPAAOADwAEAA8ABwANgAcADgAGAA6ABoAOgAcADoAGAA8ABoAPAAcADwADAAOAA4ADgAQAA4ADAAQAA4AEAAQABAADAASAA4AEgAMABQADgAUABoADgAaABA=
  tileset/cabinet02: AAwALA==
  tileset/interior_brick_outer_edge_w: AA4ALAAOAC4ADgACABoAJAAaACYAGgAiABoAHgAaACAAGAAMABgACgAYAAYAGAAIABoALAAaAC4AGgAwABoAMgAaADQAGgA2ABYAOgAWADwAFgA+ABoAHAAYAA4AGAAQABoAFAAaABYAGgAYABoAGg==
elevation: AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgICAgAAAAAAAAICAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAgICAgICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAgICAgICAgAAAAACAgICAgICAgICAgICAgICAgICAgICAgICAgAAAAACAgICAgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAAAAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAICAgICAgIC